import type { IDSEntry, PatentReport } from '@priovex/types';

export function generateIDSMarkdown(report: PatentReport): string {
  const date = new Date().toLocaleDateString('en-US', {
    month: '2-digit', day: '2-digit', year: 'numeric',
  });

  const patentEntries = report.idsEntries.filter((e) => e.type === 'patent');
  const nplEntries    = report.idsEntries.filter((e) => e.type === 'npl');

  const patentTable = patentEntries.length > 0
    ? `| # | Patent Number | Country | Publication Date | Name of Patentee / Assignee | 102 Risk | 103 Risk | Cite Prob. |
|---|--------------|---------|-----------------|----------------------------|---------|---------|-----------|
${patentEntries.map((e, i) =>
  `| ${i + 1} | ${e.patentNumber ?? e.id} | ${e.country ?? 'US'} | ${e.publicationDate} | ${e.assignee ?? 'N/A'} | ${e.risk102}% | ${e.risk103}% | ${e.examinerCitationProbability}% |`
).join('\n')}`
    : '*No patent references.*';

  const nplTable = nplEntries.length > 0
    ? `| # | Author(s) | Title | Publisher, Date, Pages, etc. | 102 Risk | 103 Risk | Cite Prob. |
|---|-----------|-------|------------------------------|---------|---------|-----------|
${nplEntries.map((e, i) =>
  `| ${i + 1} | ${(e.authors ?? []).join('; ') || 'N/A'} | ${e.title} | ${e.source ?? 'N/A'}, ${e.publicationDate}${e.doi ? `, DOI: ${e.doi}` : ''} | ${e.risk102}% | ${e.risk103}% | ${e.examinerCitationProbability}% |`
).join('\n')}`
    : '*No non-patent literature references.*';

  const highRiskEntries = report.idsEntries
    .filter((e) => e.examinerCitationProbability >= 70)
    .sort((a, b) => b.examinerCitationProbability - a.examinerCitationProbability);

  return `# INFORMATION DISCLOSURE STATEMENT (IDS)

**Application:** ${report.inventionTitle}
**Prepared:** ${date}
**Prepared by:** PrioVex.AI Patent Intelligence Platform

---

## U.S. PATENT DOCUMENTS

${patentTable}

---

## FOREIGN PATENT DOCUMENTS

*(See patent entries above — filtered by country code)*

---

## NON-PATENT LITERATURE DOCUMENTS

${nplTable}

---

## HIGH-PRIORITY REFERENCES (Examiner Citation Probability ≥ 70%)

${highRiskEntries.length > 0
  ? highRiskEntries.map((e) =>
    `**${e.type === 'patent' ? e.patentNumber ?? e.id : e.title}** — ${e.disclosureReason}`
  ).join('\n\n')
  : '*No high-priority references identified.*'}

---

## DISCLOSURE ANALYSIS

| Reference | Type | 102 Risk | 103 Risk | Cite Prob. | Disclosure Reason |
|-----------|------|---------|---------|-----------|-------------------|
${report.idsEntries.map((e) =>
  `| ${e.type === 'patent' ? e.patentNumber ?? e.id : e.title.slice(0, 50)} | ${e.type.toUpperCase()} | ${e.risk102}% | ${e.risk103}% | ${e.examinerCitationProbability}% | ${e.disclosureReason.slice(0, 100)} |`
).join('\n')}

---

## DUTY TO DISCLOSE NOTICE

Under 37 CFR 1.56, each individual associated with the filing of this application has a duty to disclose to the USPTO all information known to be material to patentability. This IDS was generated by AI-assisted analysis and should be reviewed by a registered patent attorney or agent before filing.

**Total references to disclose:** ${report.idsEntries.length} (${patentEntries.length} patents, ${nplEntries.length} NPL)

*This IDS report was generated by PrioVex.AI. It does not constitute legal advice.*
`;
}

export function generateIDSCSV(idsEntries: IDSEntry[]): string {
  const headers = [
    'Reference ID',
    'Type',
    'Patent Number',
    'Country',
    'Title',
    'Assignee/Authors',
    'Publication Date',
    'Source',
    'URL',
    'DOI',
    '102 Risk',
    '103 Risk',
    'Examiner Citation Probability',
    'Disclosure Reason',
  ].join(',');

  const rows = idsEntries.map((e) => [
    `"${e.id}"`,
    `"${e.type}"`,
    `"${e.patentNumber ?? ''}"`,
    `"${e.country ?? ''}"`,
    `"${e.title.replace(/"/g, '""')}"`,
    `"${(e.assignee ?? (e.authors ?? []).join('; ')).replace(/"/g, '""')}"`,
    `"${e.publicationDate}"`,
    `"${e.source ?? ''}"`,
    `"${e.url ?? ''}"`,
    `"${e.doi ?? ''}"`,
    `${e.risk102}`,
    `${e.risk103}`,
    `${e.examinerCitationProbability}`,
    `"${e.disclosureReason.replace(/"/g, '""')}"`,
  ].join(','));

  return [headers, ...rows].join('\n');
}
